[package]
edition = "2021"
name = "pico-github-stars"
authors = ["kromych"]
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-embedded-hal = { version = "0.2", features = ["defmt"] }
embassy-sync = { version = "0.6", features = ["defmt"] }
embassy-executor = { version = "0.6", features = ["task-arena-size-98304", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { version = "0.3", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.2", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embassy-net = { version = "0.4", features = ["defmt", "tcp", "udp", "dhcpv4", "medium-ethernet", "dns", "proto-ipv4"] }
embassy-futures = { version = "0.1" }
cyw43 = { version = "0.2", features = ["defmt", "firmware-logs"] }
cyw43-pio = { version = "0.2", features = ["defmt"] }

defmt = "0.3"
defmt-rtt = "0.4"
fixed = "1.23.1"
fixed-macro = "1.2"

reqwless = { version = "0.12", features = ["defmt",]}
serde = { version = "1", default-features = false, features = ["derive"] }
serde-json-core = "0.6"

#cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
critical-section = "1.2"
panic-probe = { version = "0.3", features = ["print-defmt"] }
display-interface-spi = "0.5"
embedded-graphics = "0.8"
st7789 = "0.7"
display-interface = "0.5"
byte-slice-cast = { version = "1.2", default-features = false }
heapless = "0.8"

embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.2", features = ["async"] }
embedded-io-async = { version = "0.6", features = ["defmt-03"] }
static_cell = "2.1"
portable-atomic = { version = "1.9", features = ["critical-section"] }
log = "0.4"
rand = { version = "0.8", default-features = false }

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
