[package]
edition = "2021"
name = "pico-github-stars"
authors = ["kromych"]
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
cyw43 = { version = "0.2", features = ["defmt", "firmware-logs"] }
cyw43-pio = { version = "0.2", features = ["defmt"] }
embassy-embedded-hal = { version = "0.2", features = ["defmt"] }
embassy-executor = { version = "0.6", features = ["task-arena-size-98304", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-futures = { version = "0.1" }
embassy-net = { version = "0.4", features = ["defmt", "tcp", "udp", "dhcpv4", "medium-ethernet", "dns", "proto-ipv4"] }
embassy-rp = { version = "0.2", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embassy-sync = { version = "0.6", features = ["defmt"] }
embassy-time = { version = "0.3", features = ["defmt", "defmt-timestamp-uptime"] }

defmt = "0.3"
defmt-rtt = "0.4"
fixed = "1.28"
fixed-macro = "1.2"

serde = { version = "1", default-features = false, features = ["derive"] }
serde-json-core = "0.6"

byte-slice-cast = { version = "1.2", default-features = false }
#cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
critical-section = "1.2"
display-interface = "0.5"
display-interface-spi = "0.5"
heapless = "0.8"
log = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
portable-atomic = { version = "1.9", features = ["critical-section"] }
rand = { version = "0.8",  default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
st7789 = "0.7"
static_cell = "2.1"

embedded-graphics = "0.8"
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.2", features = ["async"] }
embedded-io-async = { version = "0.6", features = ["defmt-03"] }
embedded-nal-async = { version = "0.7"}
embedded-tls = { git = "https://github.com/drogue-iot/embedded-tls", features = ["defmt"], default-features = false}

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
